### ISSUE TITLE
Increase default TimeOut to 1000

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-java#10]
https://github.com/ConvertAPI/convertapi-dotnet/issues/23

**Comment by JonasJasas** [comment]
`private static int defaultTimeout = 0;  // Infinite read waiting`

**Comment by tomasr78** [comment]
This is an old request, the timeout of HTTP should be read from the actual TimeOut property adding conversion_timeout_delta = 10

Please read this https://github.com/ConvertAPI/convertapi-dotnet/issues/24
