### ISSUE TITLE
"InvalidParameters":{"Timeout":["The field Timeout must be between 10 and 1200."]}

### ISSUE THREAD

**Issue by phanindars** [ConvertAPI/convertapi-java#13]
Getting the error "InvalidParameters":{"Timeout":["The field Timeout must be between 10 and 1200."]}, when running the sample conversion as below:

System.out.println("Converting WEB to PDF");
        CompletableFuture<ConversionResult> result = ConvertApi.convert("web", "pdf",
                new Param("url", "https://en.wikipedia.org/wiki/Data_conversion"),
                new Param("filename", "web-example")
        );

        Path tmpDir = Paths.get(System.getProperty("java.io.tmpdir"));
        CompletableFuture<Path> pdfFile = result.get().saveFile(tmpDir);

        System.out.println("PDF file saved to: " + pdfFile.get().toString());

Note: This is the code snippet from the examples provided by you.

**Comment by JonasJasas** [comment]
Fixed in previous versions.
