### ISSUE TITLE
Create example where source file is passed as stream

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-java#15]
Please create an example where the source file is passed as a stream.

**Comment by petersonschmitt** [comment]
`import com.convertapi.*;

Config.setDefaultSecret("your-api-secret");

// Create stream from HTML string
String streamContent = "<!DOCTYPE html><html><body><h1>My First Heading</h1><p>My first paragraph.</p></body></html>";
InputStream stream = new ByteArrayInputStream(streamContent.getBytes());

// Html to PDF API. Read more https://www.convertapi.com/html-to-pdf
CompletableFuture<ConversionResult> result = ConvertApi.convert("html", "pdf",
        new Param("file", stream, "test.html")
);

// PDF as stream
InputStream resultStream = result.get().asStream().get();`

**Comment by petersonschmitt** [comment]
here is an example of implementation using Stream

https://www.convertapi.com/doc/java-library
