### ISSUE TITLE
Change converter parameter comparison from case sensitive to case-insensitive

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-java#16]
The converter parameter comparison is case sensitive, **it must be case-insensitive**. Please @kmozsi  fix it asap and upload new version.

https://github.com/ConvertAPI/convertapi-java/blob/57e5bc5e2c661f795e3469dd04b99d18f378622b/src/main/java/com/convertapi/client/ConvertApi.java#L42

**Comment by kmozsi** [comment]
Version 2.6 has been released with the fix.
