### ISSUE TITLE
Change HTTP request Agent header format

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-java#3]
Change HTTP request Agent header format from old format

convertapi-java-version

to

ConvertAPI-Java/version

Such format is more native to HTTP agent specification http://www.bizcoder.com/the-much-maligned-user-agent-header

**Comment by JonasJasas** [comment]
https://github.com/ConvertAPI/convertapi-java/commit/55ada0abb3450f981ef2342f77a7b00e97d38a88
