### ISSUE TITLE
Is there an example of working with IO streams over File/Path?

### ISSUE THREAD

**Issue by xSAVIKx** [ConvertAPI/convertapi-java#32]
So I have a case where I have no file system representation of the document and only have either an IO stream or `byte[]` on hand to work with. I seem to struggle to find an example for my case, can someone pinpoint it please or let me know how can one work with IO streams or byte arrays?

**Comment by JonasJasas** [comment]
[Example of source file from the stream](https://github.com/ConvertAPI/convertapi-java/blob/master/examples/src/main/java/com/convertapi/examples/ConvertStream.java)

Result file has [asStream](https://github.com/ConvertAPI/convertapi-java/blob/4582c38034daa2756d5ae5d6d3b1ca99cb672da5/src/main/java/com/convertapi/client/ConversionResultFile.java#L36C18-L36C18) method.

**Comment by xSAVIKx** [comment]
> [Example of source file from the stream](https://github.com/ConvertAPI/convertapi-java/blob/master/examples/src/main/java/com/convertapi/examples/ConvertStream.java)
> 
> Result file has [asStream](https://github.com/ConvertAPI/convertapi-java/blob/4582c38034daa2756d5ae5d6d3b1ca99cb672da5/src/main/java/com/convertapi/client/ConversionResultFile.java#L36C18-L36C18) method.

Thank you for your reply. The problem is that I don't have access to the file system. Meaning that I can write any files. Is there maybe a way to provide an API that works with streams?

**Comment by JonasJasas** [comment]
You don't need a file system. An example creates a stream from the file, but the stream can be created from any source.
If you are concerned about the file name: `new Param("file", stream, "test.docx")` File name `test.docx` can be anything, important is to provide file extension correctly.

**Comment by xSAVIKx** [comment]
Got it working. Thx for your help 👍
