### ISSUE TITLE
Submit lib to https://search.maven.org

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-java#4]
Submit lib to https://search.maven.org

**Comment by belev** [comment]
Hi,

When do you expect to have the lib published to maven?

**Comment by tomasr78** [comment]
FInd programmer from https://www.upwork.com/

**Comment by tomasr78** [comment]
We have successfully published to Maven

Add the following dependency to your pom.xml:

<dependency>
    <groupId>com.convertapi.client</groupId>
    <artifactId>convertapi</artifactId>
    <version>2.2</version>
</dependency>
